### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by luisestudioalfa** [Custodia/caketickets#32]
Hello,

I have tried to install it following the steps in the file ["Read the installation doc."](https://github.com/Custodia/caketickets/blob/development/docs/install.md)

But without success...

After solving some problems with the ssh key and some others, the server returns an error
`[03-Feb-2020 10:35:02 UTC] PHP Fatal error:  [Cake\View\Exception\MissingTemplateException] Template file "Error/error500.ctp" is missing.
#0 /www/caketickets/vendor/cakephp/cakephp/src/View/View.php(875): Cake\View\View->_getViewFileName('Error/error500')
#1 /www/caketickets/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(410): Cake\View\View->render('error500', 'error')
#2 /www/caketickets/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(375): Cake\Error\ExceptionRenderer->_outputMessageSafe('error500')
#3 /www/caketickets/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(243): Cake\Error\ExceptionRenderer->_outputMessage('error500')
#4 /www/caketickets/vendor/cakephp/cakephp/src/Error/ErrorHandler.php(137): Cake\Error\ExceptionRenderer->render()
#5 /www/caketickets/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(202): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException in /www/caketickets/vendor/cakephp/cakephp/src/Error/ErrorHandler.php on line 180`

the file error500.ctp exists....

Is there anything i have to do to make it work?

Thank you in advance.

**Comment by Custodia** [comment]
Hey!

This is really something I did for an interview 4 years ago, ever since then I haven't done anything at all with PHP so unfortunately I can't really help you.

If you're looking for PHP examples I'm sure there are a plenty of better up to date examples out there!

Good luck to whatever you're doing!
